services:
  - docker

env:
  - NFDUMP_VERSION=1.6.18
#  - DOCKER_COMPOSE_VERSION=1.25.4
#
#before_install:
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin


jobs:
    include:
        - stage: build and publish 
          script: >-
             ./build.sh $NFDUMP_VERSION  && 
             docker images &&
             echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && 
             docker push netsage/nfdump-collector:$NFDUMP_VERSION
