FROM alpine:3.12.4

ARG NFDUMP_VERSION=1.6.23

WORKDIR /tmp

## Install OS dependencies
ADD https://github.com/phaag/nfdump/archive/v$NFDUMP_VERSION.tar.gz /tmp
RUN  \
   apk add --no-cache  libtool bzip2-dev && \
   apk add --no-cache --virtual build-deps  libtool autoconf automake m4 pkgconfig make g++ flex byacc 

#Build
RUN  \
    tar xfz v$NFDUMP_VERSION.tar.gz  \
    && cd /tmp/nfdump-$NFDUMP_VERSION \
    && ./autogen.sh  \
    && ./configure --enable-nsel=yes --enable-shared=true --enable-sflow=yes \
    && make  \
    && cd /tmp/nfdump-$NFDUMP_VERSION && make install  \
    && cd .. \
    && rm -rf nfdump-$NFDUMP_VERSION  \
    && rm /tmp/v$NFDUMP_VERSION.tar.gz  \
    && apk del build-deps
    

VOLUME /data

CMD ["sfcapd", "-T", "all", "-l", "/data", "-S", "1", "-w", "-z", "-p", "9999"]
